Css grid layout
wolox-training/rn-react pull request #10
Opened 2018-06-21 16:42 UTC by rlajous

## Summary
-Grid layout not responsive
## Screenshot
![grid layout](https://user-images.githubusercontent.com/40175251/41732976-f1b623f4-7558-11e8-9e5f-a704c02ebc2f.png)
## Trello Card
https://trello.com/c/wAukcmPJ/12-redise%C3%B1o-de-la-p%C3%A1gina

2018-06-22 17:07 UTC, damfinkel requested changes

2018-06-22 17:07 UTC, damfinkel commented on Maquetado/scss/tech.scss
> +
remove empty line

2018-06-22 17:07 UTC, damfinkel commented on Maquetado/scss/tech.scss
> +  //grid-template-columns: 2fr 1fr 1fr;
remove comment

2018-06-22 17:07 UTC, damfinkel commented on Maquetado/scss/tech.scss
> +    .tech {
indent this at the same level as the parent's properties:

```
.parent {
  property1: ...,
  property2: ...,

  .child {
  
  ...
  }
}
```

Apply this to the rest

2018-06-22 17:07 UTC, damfinkel commented on Maquetado/scss/tech.scss
> +        }
space between classes

2018-06-22 17:07 UTC, damfinkel commented on Maquetado/scss/tech.scss
> +            &::before{
space before {

2018-06-22 17:19 UTC, SKOLZ requested changes

2018-06-22 17:19 UTC, SKOLZ commented on Maquetado/scss/tech.scss
> +            &::before{
and empty line between properties and nested selectors

2018-06-22 17:19 UTC, SKOLZ commented on Maquetado/scss/tech.scss
> +            grid-area: principal;
wrong indentation here

2018-06-26 16:36 UTC, damfinkel approved these changes

2018-06-26 17:07 UTC, merged