Score board
wolox-training/rn-react pull request #16
Opened 2018-07-11 20:04 UTC by rlajous

2018-07-17 16:12 UTC, mvbattan requested changes
Nice work !! Here are a few comments

2018-07-17 16:12 UTC, mvbattan commented on react/my-app/src/app/components/Routes/components/PrivateRoute.js
> +export const PrivateRoute = ({ component: Component, ...rest, token }) => (
Remember to `export default` the main content of the file, in this case, `PrivateRoute`

2018-07-17 16:12 UTC, mvbattan commented on react/my-app/src/app/components/Routes/components/PrivateRoute.js
> +export const PrivateRoute = ({ component: Component, ...rest, token }) => (
Prefer `function` syntax for components:
```
function PrivateRoute() {
}
```
This will allow to change a bit fast between `Component` and `Stateless Component`

2018-07-17 16:12 UTC, mvbattan commented on react/my-app/src/app/components/Routes/index.js
> +      <Fragment>
This `Fragment` is not necessary 😄

2018-07-17 16:12 UTC, mvbattan commented on react/my-app/src/app/screens/DashBoard/components/NavBar/index.js
> +const Links = ({ dispatch }) => (
Use `function` notation

2018-07-17 16:12 UTC, mvbattan commented on react/my-app/src/app/screens/DashBoard/components/NavBar/index.js
> +    <NavLink className="link" onClick={() => dispatch(action.logoutUser())} to={routes.LOGIN}>
I'd receive this function via `mapDispatchToProps`, so this function is being created only once an not on every render.

2018-07-17 16:12 UTC, mvbattan commented on react/my-app/src/app/components/Routes/index.js
> +
Missing PropTypes declarations here 👮

2018-07-17 16:12 UTC, mvbattan commented on react/my-app/src/app/screens/DashBoard/index.js
> +        <Route path={ROUTES.HOME} render={() => <Game />} />
We can use `component` prop here:
```
<Route path={ROUTES.HOME} component={Game} />
```
For reference: https://reacttraining.com/react-router/core/api/Route

2018-07-17 16:12 UTC, mvbattan commented on react/my-app/src/app/screens/DashBoard/screens/Game/index.js
> +          <Board squares={current.squares} onClick={i => this.handleClick(i)} />
We can put `onClick={this.handleClick}` directly, since that function _already_ receives an argument

2018-07-17 16:12 UTC, mvbattan commented on react/my-app/src/app/screens/DashBoard/screens/Game/index.js
> +          <Board squares={current.squares} onClick={i => this.handleClick(i)} />
Also, we can receive this function via `mapDispatchToProps`. Doing this will result to a more lightweight component since this can be treated as stateless

2018-07-17 16:12 UTC, mvbattan commented on react/my-app/src/app/screens/Login/components/Loader/index.js
> +function Load() {
Keep consistency between the name of the component and the folder name.
We usually prefer `Components` to be named with a noun

2018-07-17 16:12 UTC, mvbattan commented on react/my-app/src/app/components/Routes/components/PrivateRoute.js
> +export const PrivateRoute = ({ component: Component, ...rest, token }) => (
Also, this component should be inside
```
react/my-app/src/app/components/Routes/components/PrivateRoute/index.js
```

2018-07-17 16:12 UTC, mvbattan commented on react/my-app/src/app/screens/Login/components/fields/index.js
> +export const customInput = props => {
Write this component as `function`. Remember to `export default` it

2018-07-17 16:12 UTC, mvbattan commented on react/my-app/src/app/screens/Login/components/fields/index.js
> +export const customInput = props => {
Also, I'd rename the container folder to `CustomInput` and this component as well. Components names should be capitalized.

2018-07-17 16:12 UTC, mvbattan commented on react/my-app/src/app/screens/Login/index.js
> +  };
This one can be received via `mapDispatchToProps`

2018-07-17 16:12 UTC, mvbattan commented on react/my-app/src/app/screens/Login/components/fields/index.js
> +};
Missing props declaration

2018-07-17 16:12 UTC, mvbattan commented on react/my-app/src/app/screens/Login/layout.js
> +
Missing props declaration

2018-07-17 16:12 UTC, mvbattan commented on react/my-app/src/app/screens/Login/layout.js
> +      <div>
non styled `div` -> `Fragment` ? Does this work ?

2018-07-17 16:12 UTC, mvbattan commented on react/my-app/src/app/screens/Login/index.js
> +
Missing props declaration

2018-07-17 16:12 UTC, mvbattan commented on react/my-app/src/app/screens/Login/layout.js
> +      <Field name={FIELDS.EMAIL} component={customInput} type="email" label="E-Mail" validate={[required]} />
Extract this `validate` array outside this render

2018-07-17 16:12 UTC, mvbattan commented on react/my-app/src/redux/auth/action.js
> +      dispatch({ type: actions.GET_USERS }); // Esta accion es para, por ejemplo, poner un loading para cuando vuelva el request
Put comments in english 😇

2018-07-17 16:12 UTC, mvbattan commented on react/my-app/src/redux/store.js
> +const store = createStore(reducers, composeEnhancers(middlewares));
👏

2018-07-17 16:12 UTC, mvbattan commented on react/my-app/src/services/LocalStorageService.js
> +export const deleteToken = () => localStorage.removeItem('token');
I'd extract `'token'` literal into a `const` within this file

2018-07-17 18:28 UTC, rlajous commented on react/my-app/src/app/components/Routes/index.js
> +
done

2018-07-17 18:28 UTC, rlajous commented on react/my-app/src/app/screens/Login/index.js
> +
done

2018-07-18 15:23 UTC, mvbattan commented on react/my-app/src/app/components/Routes/components/PrivateRoute/index.js
> +      render={props => (token || getToken() ? <Component {...props} /> : <Redirect to={ROUTES.LOGIN} />)}
Why `token || getToken()` ?

2018-07-18 15:23 UTC, mvbattan commented on react/my-app/src/app/screens/DashBoard/components/NavBar/index.js
> +function Links({ logOut }) {
I'd rename this one so we emphasize that this is a function, by example, `handleLogout`

2018-07-18 15:23 UTC, mvbattan commented on react/my-app/src/app/screens/DashBoard/screens/Game/index.js
> +/* eslint-disable react/no-array-index-key */
I'd put this one the line before it yields:
```
// eslint-disable-next-line react/no-array-index-key
```

2018-07-18 15:23 UTC, mvbattan commented on react/my-app/src/app/screens/Login/components/fields/index.js
> +function customInput({ label, input, type, meta, autoFocus }) {
Remember to put this one like `CustomInput` renaming this folder name as well

2018-07-18 15:28 UTC, mvbattan commented
@rlajous Remember to add a description for this PR, with screenshot and trello card !

2018-07-19 16:36 UTC, mvbattan commented on react/my-app/src/redux/auth/reducer.js
> +};
This one is not being used 😇

2018-07-19 16:36 UTC, mvbattan commented on react/my-app/src/services/AuthService.js
> +    const scores = await api.get('/score');
I think that here we can do filtering from API side, like the above one

2018-07-19 16:36 UTC, mvbattan commented on react/my-app/src/redux/auth/action.js
> +  getScore2: () => ({
Ideally we should use this one

2018-07-19 16:36 UTC, mvbattan commented on react/my-app/src/app/screens/Login/layout.js
> +        {loading && <Load />}
`Loader`

2018-07-19 16:36 UTC, mvbattan commented on react/my-app/src/app/screens/Login/layout.js
> +import customInput from './components/fields/index';
`CustomInput`, also this should belong to `./components/CustomInput`

2018-07-19 16:36 UTC, mvbattan commented on react/my-app/src/app/screens/Login/layout.js
> +import customInput from './components/fields/index';
Remember that is not needed to put `index` at the end, since `index.js` is the default entry point for folders

2018-07-19 16:36 UTC, mvbattan commented on react/my-app/src/app/screens/DashBoard/index.js
> +import ScoreBoard from './screens/ScoreBoard/index';
`index` here is not needed

2018-07-19 16:36 UTC, mvbattan commented on react/my-app/src/app/components/Routes/index.js
> +import Login from '../../screens/Login/index';
`index` here is not needed

2018-07-19 18:47 UTC, mvbattan approved these changes

2018-07-19 18:54 UTC, merged