Added register and funcionality
wolox-training/rn-react pull request #18
Opened 2019-01-09 15:41 UTC by rlajous

## Summary 

- Added register in home

## Screenshot 

![vue1](https://user-images.githubusercontent.com/40175251/50910102-e58e1300-140b-11e9-8e3e-643329fdd5ab.gif)

## Trello Card

https://trello.com/c/hEW59uiL/22-register-layout-exercise

2019-01-10 16:44 UTC, mcallegari10 requested changes

2019-01-10 16:44 UTC, mcallegari10 commented on wolox-books/src/views/Home.vue
> +    label.label(for="firstName") First Name
Use pipe notation

2019-01-10 16:44 UTC, mcallegari10 commented on wolox-books/src/views/Home.vue
> +    input#firstName(type="text",name="firstName",v-model="firstName")
Separate the attributes with a space, not need for the comma

2019-01-10 16:44 UTC, mcallegari10 commented on wolox-books/src/views/Home.vue
> +    input#firstName(type="text",name="firstName",v-model="firstName")
Also, no need for the id

2019-01-10 16:44 UTC, mcallegari10 commented on wolox-books/src/views/Home.vue
> +#register-form.home
No need for the id

2019-01-10 16:44 UTC, mcallegari10 commented on wolox-books/src/views/Home.vue
> +  form.register-form(@submit.prevent="onSubmit")
Remember to add a `novalidate` to the form so the errors are custom and not HTML based

2019-01-10 16:44 UTC, mcallegari10 commented on wolox-books/src/views/Home.vue
> +    label.label(for="lastName") Last Name
Pipe notation

2019-01-10 16:44 UTC, mcallegari10 commented on wolox-books/src/views/Home.vue
> +    input#lastName(type="text",name="lastName",v-model="lastName")
Separate with spaces and no need for the id

2019-01-10 16:44 UTC, mcallegari10 commented on wolox-books/src/views/Home.vue
> +      password: ""
Change all of this to single quotes

2019-01-10 16:46 UTC, rlajous commented on wolox-books/src/views/Home.vue
> +    label.label(for="firstName") First Name
it is fixed in the other pr

2019-01-10 16:46 UTC, rlajous commented on wolox-books/src/views/Home.vue
> +    input#firstName(type="text",name="firstName",v-model="firstName")
it is fixed in the other pr

2019-01-10 16:47 UTC, rlajous commented on wolox-books/src/views/Home.vue
> +    label.label(for="lastName") Last Name
it is fixed in the other pr

2019-01-10 16:55 UTC, rlajous commented on wolox-books/src/views/Home.vue
> +    input#firstName(type="text",name="firstName",v-model="firstName")
The id is for the label

2019-01-10 16:55 UTC, rlajous commented on wolox-books/src/views/Home.vue
> +      password: ""
eslint is autofixing this

2019-01-10 22:01 UTC, FrankIglesias requested changes

2019-01-10 22:01 UTC, FrankIglesias commented on wolox-books/.gitignore
> +/package-lock.json
the package-lock should not be gitignored

2019-01-10 22:01 UTC, FrankIglesias commented on wolox-books/src/views/Home.vue
> +        // do your submit logic here
remove comment and semi colon of the file

2019-01-11 17:48 UTC, mcallegari10 commented on wolox-books/src/views/Home.vue
> +        this.submitStatus = 'ERROR'
Remember to change this status attribute :stuck_out_tongue_closed_eyes:

2019-01-11 17:48 UTC, mcallegari10 commented on wolox-books/src/views/Home.vue
> +        setTimeout(() => {
Not need for this time out

2019-01-11 18:00 UTC, FrankIglesias requested changes

2019-01-11 18:00 UTC, FrankIglesias commented on wolox-books/.env
> +VUE_APP_API_BASE_URL="https://wbooks-api-stage.herokuapp.com/api/v1"
you  must gitignore this

2019-01-11 18:00 UTC, FrankIglesias commented on wolox-books/src/views/Home.vue
> +      console.log(data)
remove the ocnsole log

2019-01-11 18:00 UTC, FrankIglesias commented on wolox-books/src/views/Home.vue
> +<style lang='scss'>
use scoped styles

2019-01-11 18:03 UTC, rlajous commented on wolox-books/src/views/Home.vue
> +      console.log(data)
The card asked for this

2019-01-11 18:11 UTC, mcallegari10 approved these changes

2019-01-11 18:15 UTC, merged