Added i18n to register
wolox-training/rn-react pull request #19
Opened 2019-01-09 17:25 UTC by rlajous

## Summary 

- Added translation to Register view

## Trello Card

https://trello.com/c/eRRvXM4i/17-internationalization

2019-01-10 16:46 UTC, mcallegari10 requested changes

2019-01-10 16:46 UTC, mcallegari10 commented on wolox-books/src/router.js
> +        import(/* webpackChunkName: "about" */ './views/About/index.vue')
Write this in the same line

2019-01-10 16:46 UTC, mcallegari10 commented on wolox-books/src/router.js
> +import Home from './views/Home/index.vue'
Remember to delete the folder and just stay with the component

2019-01-10 16:58 UTC, rlajous commented on wolox-books/src/router.js
> +        import(/* webpackChunkName: "about" */ './views/About/index.vue')
eslint autofixing this

2019-01-10 16:58 UTC, rlajous commented on wolox-books/src/router.js
> +import Home from './views/Home/index.vue'
this is fixed in the other pr

2019-01-10 22:00 UTC, FrankIglesias requested changes

2019-01-10 22:00 UTC, FrankIglesias commented on wolox-books/src/main.js
> +});
remove this semi colon

2019-01-10 22:00 UTC, FrankIglesias commented on wolox-books/src/main.js
> +import Vue from "vue";
remove semi colon

2019-01-10 22:00 UTC, FrankIglesias commented on wolox-books/src/main.js
> +Vue.config.productionTip = false;
same (why this false?

2019-01-10 22:00 UTC, FrankIglesias commented on wolox-books/src/router.js
> +      name: "home",
check your linter

2019-01-10 22:00 UTC, FrankIglesias commented on wolox-books/src/views/Register.vue
> +    label.label(for="email")
remove this extra space

2019-01-10 22:00 UTC, FrankIglesias commented on wolox-books/src/views/Register.vue
> +    button
same

2019-01-10 22:00 UTC, FrankIglesias commented on wolox-books/src/views/Register.vue
> +  a(href="/")
same

2019-01-11 13:36 UTC, rlajous commented on wolox-books/src/main.js
> +Vue.config.productionTip = false;
it came as default like that

2019-01-11 17:46 UTC, mcallegari10 commented on wolox-books/src/router.js
> +import Home from './views/Register'
The name of the import should be the same you are importing, `Register` in this case

2019-01-11 18:38 UTC, mcallegari10 commented on wolox-books/src/router.js
> +      component: Register
Maintain the dynamic import `component: () => import(/* webpackChunkName: "about" */ './views/Register.vue')`, that way performance will improve :smile:

2019-01-11 18:38 UTC, mcallegari10 commented on wolox-books/src/views/Register.vue
> +      |{{$t('register.firstName')}}
Leave a space between pipe and text

2019-01-11 18:41 UTC, FrankIglesias approved these changes

2019-01-14 13:59 UTC, mcallegari10 approved these changes

2019-01-14 14:00 UTC, merged