Vue validations
wolox-training/rn-react pull request #20
Opened 2019-01-10 16:01 UTC by rlajous

## Summary

- Added validations to password and email

## Screenshot 
![vuelidations](https://user-images.githubusercontent.com/40175251/50980611-dbd1e180-14d7-11e9-8b51-485da56f12a0.gif)

## Trello Card
https://trello.com/c/UzqcviSZ/27-form-validation

2019-01-10 21:59 UTC, FrankIglesias requested changes

2019-01-10 21:59 UTC, FrankIglesias commented on wolox-books/src/views/Register.vue
> +      console.log(data);
remove this semi colon

2019-01-10 21:59 UTC, FrankIglesias commented on wolox-books/src/views/Register.vue
> +};
same

2019-01-10 21:59 UTC, FrankIglesias commented on wolox-books/src/views/Register.vue
> +import { required, email, helpers } from "vuelidate/lib/validators";
smae

2019-01-10 21:59 UTC, FrankIglesias commented on wolox-books/src/views/Register.vue
> +);
remove

2019-01-10 21:59 UTC, FrankIglesias commented on wolox-books/src/views/Register.vue
> +      if (this.$v.$invalid) {
remove this curly braces

2019-01-10 21:59 UTC, FrankIglesias commented on wolox-books/src/views/Register.vue
> +  width: 300px;
use width and max width (maybe this class can be a generic one)

2019-01-10 21:59 UTC, FrankIglesias commented on wolox-books/src/views/Register.vue
> +<style lang="scss">
you'd like to have this classes scoped

2019-01-14 14:41 UTC, mcallegari10 approved these changes

2019-01-14 14:41 UTC, mcallegari10 commented on wolox-books/src/views/Register.vue
> +  a.button-login(href='/')
This won't work, use `router-link` component

2019-01-14 14:49 UTC, mcallegari10 approved these changes

2019-01-14 14:58 UTC, merged