Apisauce
wolox-training/rn-react pull request #21
Opened 2019-01-10 17:15 UTC by rlajous

## Summary

- Added call to api when signup

## ScreenShot

![vuelidations](https://user-images.githubusercontent.com/40175251/50985043-2193a780-14e2-11e9-9f9c-e757ca43343e.gif)

## Trello Card
https://trello.com/c/0sSPuHzY/15-register-integration

2019-01-10 21:57 UTC, FrankIglesias requested changes

2019-01-10 21:57 UTC, FrankIglesias commented on wolox-books/src/config/api.js
> +  baseURL: "https://wbooks-api-stage.herokuapp.com/api/v1",
this can be moved to a .env file

2019-01-10 21:57 UTC, FrankIglesias commented on wolox-books/src/views/Register.vue
> +      authService.logIn({
remove the console log above

2019-01-14 15:22 UTC, mcallegari10 requested changes

2019-01-14 15:22 UTC, mcallegari10 commented on wolox-books/src/views/Register.vue
> +  width: 300px;
Use

```scss
max-width: 300px;
width: 100%;
```

2019-01-14 15:22 UTC, mcallegari10 commented on wolox-books/src/views/Register.vue
> +  width: 300px;
Same

2019-01-14 15:22 UTC, mcallegari10 commented on wolox-books/src/config/api.js
> +  baseURL: "https://wbooks-api-stage.herokuapp.com/api/v1",
:point_up:

2019-01-14 15:22 UTC, mcallegari10 commented on wolox-books/src/views/Register.vue
> +      | Password must have at least one number and one uppercase character
The errors should be in the translations as well

2019-01-14 15:22 UTC, mcallegari10 commented on wolox-books/src/services/AuthService.js
> +export const authService = {
It's a better option to use multiple functions instead of an object:

```js
export function logIn(userDetails) {
  return api.post(...)
}

export function signUp(userDetails) {
  return ...
}
```
This way each function is more scalable than just an object :smile:

2019-01-14 15:22 UTC, mcallegari10 commented on wolox-books/src/services/AuthService.js
> +  logIn: userDetails => api.post("/users", userDetails),
Remember to use single quotes

2019-01-14 17:26 UTC, FrankIglesias requested changes

2019-01-14 17:26 UTC, FrankIglesias commented on wolox-books/src/views/Register.vue
> +  router-link.button-login(to='/')
This should redirect to a `/login` route

2019-01-14 18:26 UTC, mcallegari10 approved these changes

2019-01-14 18:32 UTC, merged