Vue router
wolox-training/rn-react pull request #22
Opened 2019-01-11 15:43 UTC by rlajous

## Summary
- Added login page
- Router-link to redirect between screens
- Request in login page

## Screenshot
![login](https://user-images.githubusercontent.com/40175251/51043832-64b35080-159e-11e9-9785-39c0dc2fa1d0.gif)

## Trello Card
https://trello.com/c/luLpiW9a/18-vue-router

2019-01-11 15:56 UTC, FrankIglesias requested changes

2019-01-11 15:56 UTC, FrankIglesias commented on wolox-books/src/config/api.js
> +  baseURL: 'https://wbooks-api-stage.herokuapp.com/api/v1',
this can be moved to a .env file

2019-01-11 15:56 UTC, FrankIglesias commented on wolox-books/src/views/Login.vue
> +    button
where is the class of this button?

2019-01-11 15:56 UTC, FrankIglesias commented on wolox-books/src/views/Login.vue
> +
remove this line

2019-01-11 15:56 UTC, FrankIglesias commented on wolox-books/src/views/Login.vue
> +      authService.logIn({
you are not checking the form validity before the service calling

2019-01-14 18:42 UTC, rlajous commented on wolox-books/src/views/Login.vue
> +    button
I will style everithing after

2019-01-15 12:59 UTC, mcallegari10 requested changes

2019-01-15 12:59 UTC, mcallegari10 commented on wolox-books/src/views/Login.vue
> +            password: this.password
Use  destructuring

2019-01-15 16:52 UTC, mcallegari10 approved these changes

2019-01-15 17:02 UTC, merged