ContentLayout
wolox-training/rn-react pull request #4
Opened 2018-06-15 20:30 UTC by rlajous

2018-06-18 14:39 UTC, damfinkel requested changes

2018-06-18 14:39 UTC, damfinkel commented on Maquetado/index.html
> +          <span class="release"> Realease:2013 </span>
remove spaces before and after the text.

2018-06-18 14:39 UTC, damfinkel commented on Maquetado/index.html
> +          <span class="release"> Realease:2010 </span>
here too

2018-06-18 14:39 UTC, damfinkel commented on Maquetado/index.html
> +          <span class="release"> Realease:2014 </span>
here too. Remove it from all the other places too.

2018-06-18 14:39 UTC, damfinkel commented on Maquetado/scss/styles.scss
> +    flex-direction: row;
this is the default when using flexbox, we can avoid it

2018-06-18 14:39 UTC, damfinkel commented on Maquetado/scss/styles.scss
> +    justify-content: flex-start;
same, this is the default, we can avoid it

2018-06-18 14:39 UTC, damfinkel commented on Maquetado/scss/tech.scss
> +
remove this empty line

2018-06-18 14:39 UTC, damfinkel commented on Maquetado/scss/tech.scss
> +  width: $tech-logo-size*2;
space between operators: `$tech-logo-size * 2`

2018-06-18 14:39 UTC, damfinkel commented on Maquetado/scss/tech.scss
> +  height: $tech-logo-size*3;
same here

2018-06-18 14:39 UTC, damfinkel commented on Maquetado/scss/tech.scss
> +    //margin: 5px auto;
remove comments

2018-06-18 14:39 UTC, damfinkel commented on Maquetado/scss/tech.scss
> +
remove this empty line

2018-06-18 14:39 UTC, damfinkel commented on Maquetado/scss/tech.scss
> +  height: $tech-logo-size*3;
The tech's width shouldn't be relative to the logo size. It should have it's own size, independant of the logo. This goes for the height as well

2018-06-18 14:39 UTC, damfinkel commented on Maquetado/scss/styles.scss
> +    padding: 0 $title-decoration-width/2;
This size shouldn't depend on the title width.

2018-06-18 14:39 UTC, damfinkel commented on Maquetado/scss/tech.scss
> +.tech {
Instead of settings widths, I'd set a padding for the tech, and then center the texts.

2018-06-18 14:39 UTC, damfinkel commented on Maquetado/scss/tech.scss
> +    height: $tech-logo-size*3;
Don't do this height and width relative to the logo. Give it its own size

2018-06-18 14:40 UTC, damfinkel commented
Please add a screenshot or a gif in each PR.

2018-06-18 14:41 UTC, damfinkel commented
Oh, and this PR contains two cards. Please have at least one PR for each card

2018-06-18 16:35 UTC, SKOLZ requested changes

2018-06-18 16:35 UTC, SKOLZ commented on Maquetado/index.html
> +          <h1 class="name">ReactJS</h1>
this should be an h2 tag (or lower) since the h1 is represented by the title

2018-06-18 16:35 UTC, SKOLZ commented on Maquetado/index.html
> +          <img class="image" src="./assets/react_icon.svg">
add `alt` attribute and close the tag as a self closing tag by leaving an empty space and a slash at the end, like this: ` />`

2018-06-18 16:35 UTC, SKOLZ commented on Maquetado/scss/styles.scss
> +body{
don't target html elements, target classes instead.

2018-06-18 16:35 UTC, SKOLZ commented on Maquetado/scss/styles.scss
> +  padding: 3% 20%;
use fixed pixel values for margins and paddings since it allows a more fixed design that doesn't vary that much with different resolutions.

2018-06-18 16:35 UTC, SKOLZ commented on Maquetado/scss/styles.scss
> +body{
add a space before the curly brace

2018-06-18 16:35 UTC, SKOLZ commented on Maquetado/scss/styles.scss
> +.container{
add a space before the curly brace

2018-06-19 18:24 UTC, damfinkel approved these changes

2018-06-19 18:27 UTC, merged